# Generated by Django 5.2.6 on 2025-09-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeedBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('batch_number', models.CharField(max_length=64, unique=True)),
                ('weight_grams', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_by_date', models.DateField()),
                ('is_quarantined', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
