# Generated by Django 5.2.6 on 2025-09-30 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seedbatch',
            options={'ordering': ['sell_by_date', 'batch_number']},
        ),
        migrations.RemoveField(
            model_name='seedbatch',
            name='is_quarantined',
        ),
        migrations.RemoveField(
            model_name='seedbatch',
            name='name',
        ),
        migrations.AddField(
            model_name='seedbatch',
            name='seed_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='seedbatch',
            name='batch_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='seedbatch',
            name='weight_grams',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='BatchPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='batch_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='seeds.seedbatch')),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('charity', 'Charity'), ('printer_error', 'Printer error'), ('machine_error', 'Machine error'), ('disposal', 'Disposal')], max_length=20)),
                ('quantity_grams', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='seeds.seedbatch')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
